[package]
name = "elixirclient"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "elixirclient"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
my_websocket_crate = { path = "../../../../../my_websocket_crate" } # DIPENDEZA AL MIO CRATE

